# exampleSite 
#
# demo site for Hugo-smorg, a theme for the Hugo static site generator. https://gohugo.io/

# themesDir is needed only to run exampleSite in-place
themesDir: "../.."

baseURL: "http://www.example.com/"
languageCode: "en-us"
title: "Hugo-smorg"
theme: "hugo-smorg"
author: 
    name: "Your Name"
    email: "thisemaildoesnotexist@www.example.com"
copyright: "&copy; Your Name"
# GoogleAnalytics: # add your GA ID and uncomment
enableGitInfo: false
summaryLength: 20
pygmentsUseClasses: true
pygmentsCodefencesGuessSyntax: true
pygmentsCodefences: true
paginate: 2  # you'll want a higher, reasonable number


# Access in templates via $.Site.Params.somevalue ------------------------
params: 
    debug: false # cause template path to be output at top of page, handy for dev
    cssPath: 'css/smorg.css' # Default, override here
    only_feed_summaries: true
    fullname: "Your Full Or Organization Name"
    description: "160 characters or less describing you or your organization or your site's purpose."
    # Further customize logo in partials/logo.html; 
    # used in partials nav.html and footer.
    logotype: '<span class="has-text-weight-bold">hugo-<span class="has-text-danger">smorg</span></span>' 
    footer: 'An open source theme by <a href="https://mikewatkins.ca/">Mike Watkins</a>'
    subfooter: '<i class="fab fa-github"></i> <a href="https://github.com/solutionroute/hugo-smorg">github.com/solutionroute/hugo-smorg</a>'
        # Schema.org
    publisher:
        # Organization, Person
        type: Organization
        name: Name of organization or person
        logo: url to logo image
# Primary Navigation Menu (partials/nav.html) ----------------------------
# Our exampleSite menu exploses About, Projects and Blog
# Note that "About" is added to the menu within content/about.md - it's 
# not a true "section" like post and project, although you can change this.

# NOTE: Don't put leading "/" in the url parameter
menu:
    sectionmenu:
        - name: "About"
          url: "about/"
          weight: 10
        - name: "Projects"
          url: "project/"
          identifier: "project"
          weight: 20
        - name: "Blog"
          url: "post/"
          weight: 30
        # Other single pages not within a section folder can be  
        # added to this menu in front matter of the document i.e. contact.md

# Syndication feeds atom.xml and rss.xml ---------------------------------
# Adds Atom feed support in conjunction with /layouts/index.atom.xml
# Change default rss filename to rss.xml, layout is built in to Hugo 
mediaTypes:
  application/atom:
    suffix: xml

outputFormats:
  Atom:
    mediaType: application/atom
    baseName: atom
  RSS:
    mediaType: application/rss
    baseName: rss

outputs:
  home:
    - HTML
    - Atom
    - RSS

# Optional, disable RSS feed
#disableKinds:
  #- RSS
